# site settings

title: /home/packjack
description: packjack's personal site, contains links to media, blog, etc..
taglong: packjack's personal webpage
tagshort: My Site
url: packjackisback.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/Packjackisback/packjackisback.github.io

# author settings

author:
  name: packjack
  email: packjackisback@gmail.com
photo: https://avatars.githubusercontent.com/u/83289186?v=4

# social media links

social:
  facebook: username
  github: packjackisback
  instagram: username
  linkedin: packjack ⠀
  stackoverflow: 0000000/username
  twitter: JacksonMbball

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
